name: Xcode - Build

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -sdk $(xcrun --show-sdk-path --sdk iphoneos) -configuration Release
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          path: /Users/runner/work/tmpAVFoundationThumbnailResource/tmpAVFoundationThumbnailResource/build/Release-iphoneos/
          
          
